/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator */

#ifndef _Included_org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator
#define _Included_org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator
#ifdef __cplusplus
extern "C" {
#endif
#undef org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator_isGPUEnabled
#define org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator_isGPUEnabled 1L
#undef org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator_gpuThreads
#define org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator_gpuThreads 3L
/*
 * Class:     org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator
 * Method:    getRegionNoiseData
 * Signature: (Lorg/pepsoft/worldpainter/exporting/NoiseHardwareAcceleratorRequest;)Lorg/pepsoft/worldpainter/exporting/NoiseHardwareAcceleratorResponse;
 */
JNIEXPORT jobject JNICALL Java_org_pepsoft_worldpainter_exporting_NoiseHardwareAccelerator_getRegionNoiseData
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
